### ISSUE TITLE
Lichess Time Bug 

### ISSUE THREAD

**Issue by ghost** [lichess-org/compression#8] opened 2020-09-29 14:27 UTC
Hello.
I played a game of chess against someone and gave my opponent more time. So that he has 5min time to think about it. For some reason lichess always interrupts the game. The reason for this is "time out". But both players still have time. What could be the reason for that. The game ends immediately if white wants to make the first move. 
Forum: https://lichess.org/forum/general-chess-discussion/lichess-time-bug

**Comment by niklasf** [comment] 2020-09-29 14:29
Moving to https://github.com/ornicar/lila. I doubt it's caused by compression.

**Closed as completed by niklasf** 2020-09-29 14:29 UTC
